services:
  server:
    build: .
    pull_policy: build
    restart: unless-stopped
    networks:
      - external-network
    labels:
      traefik.enable: true
      traefik.http.routers.programming-principles.rule: Host(`programming.principles.lenn.rocks`) 
      traefik.http.services.programming-principles.loadbalancer.server.port: 80 # port to route to internally


networks:
  external-network:
    external: true # hook into public network instead of creating our own
